name: physiqueai_apk
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  # firebase_auth: ^9.1.0  # Uncomment if using Firebase Auth
  # cloud_firestore: ^4.15.9  # Uncomment if using Firestore
  # firebase_storage: ^11.2.1  # Uncomment if using Firebase Storage
  # firebase_analytics: ^10.8.10  # Uncomment if using Firebase Analytics
  # google_fonts: ^6.2.1  # Uncomment if using Google Fonts
  # delightful_toast: ^1.1.0  # Uncomment if using Toast
  camera: ^0.10.0+3  # Camera package for accessing the phone camera
  # tflite_flutter: ^0.9.0  # TensorFlow Lite for model inference (if using a pose model)
  path_provider: ^2.0.11
  image: ^3.0.1  # For image processing (optional if you need image manipulation)

  cupertino_icons: ^1.0.8
  flutter_calendar_carousel: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets (ensure you have the correct path to the asset)
  assets:
    - assets/Physiquelogo.png
  #   - images/a_dot_ham.jpeg

  # Custom fonts (if required)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
